### PR TITLE
fix/UpdateCommentsBar

### LINKED ISSUE #309: Mobile: Improve comment bar
We need to improve the comment bar to match the design on figma. We also need to ensure that the like and comment buttons work properly properly and hit the API successfully.

### PR DESCRIPTION
**Pull request by trentstauff**
This PR improves the previous implementation of the comments bar.
Firstly, it enables the ability for the # of likes+comments
(which has been moved into the comment bar) to update immediately
when the user likes or submits a comment.

It also updates the comment bar to better represent the figma,
mainly turning the message icon into a "modal" to then enter a comment
into.

Now, if a user would like to see the comments, they can press the
grey "Comments (#)" text.

Please note, this change only exists on the housing page with listings.
There will be a future ticket where this comment bar will be
implemented to all posts.

image0

>
>
>
>
>
>

image1

Closes #309

### CODE REVIEW

File: mobile/src/src/components/Housing/Listings/ListingsContainer.jsx [hunk 1]
```diff
@@ -42,18 +42,53 @@ class ListingContainer extends Component {
   };
 
   likeListing = (id, shouldLike) => {
+    // updates number of likes
+    let index = this.state.listings.findIndex((obj) => obj.id == id);
+    let copyList = JSON.parse(JSON.stringify(this.state.listings));
+    shouldLike == true
```
Comment (shashankanandkannan) [inline mobile/src/src/components/Housing/Listings/ListingsContainer.jsx:48]: Nitpick: you don't have to do `shouldLike == true?`, you can instead write `shouldlike?`.

File: mobile/src/src/components/Housing/Listings/ListingsContainer.jsx [hunk 2]
```diff
@@ -42,18 +42,53 @@ class ListingContainer extends Component {
...
+      ? (copyList[index].likes = this.state.listings[index].likes + 1)
+      : (copyList[index].likes = this.state.listings[index].likes - 1);
+    this.setState({ listings: copyList });
+
     ListingsEndpoint.like(
       id,
       shouldLike,
       () => {},
```
Comment (shashankanandkannan) [inline mobile/src/src/components/Housing/Listings/ListingsContainer.jsx:56]: If you haven't already, maybe consider updating the number of likes in the state object in this handleSuccess method. Was this a deliberate choice in order to make the displayed number of likes update immediately instead of having to wait for the Axios request?

File: mobile/src/src/components/Housing/Listings/ListingsContainer.jsx [hunk 3]
```diff
@@ -42,18 +42,53 @@ class ListingContainer extends Component {
...
+  sendComment = (data) => {
+    // updates number of comments
+    let index = this.state.listings.findIndex(
+      (obj) => obj.id == data.object_id
+    );
+    let copyList = JSON.parse(JSON.stringify(this.state.listings));
+    copyList[index].comments = this.state.listings[index].comments + 1;
+    this.setState({ listings: copyList });
+
+    CommentsEndpoint.post(
```
Comment (shashankanandkannan) [inline mobile/src/src/components/Housing/Listings/ListingsContainer.jsx:77]: Not entirely necessary, but you could remove the need to send the contentType prop if you locked in data.content_type in this function, as it's going to remain constant. If, in your opinion, this would hurt readability, another alternative is to explicitly add content_type as a parameter of the CommentsEndpoint.post function, and give it the constant value of `Choices.contentTypes.listing`  when you call the function here. Idk though, it's up to you.

File: mobile/src/src/components/Housing/Listings/ListingsContainer.jsx (hunk 1 above)
Comment (trentstauff) [reply mobile/src/src/components/Housing/Listings/ListingsContainer.jsx:48]: Will do

File: mobile/src/src/components/common/CommentBar/CommentBar.jsx [hunk 4]
```diff
@@ -1,6 +1,7 @@
-import React, { useState } from "react";
-import { StyleSheet, View, TextInput } from "react-native";
+import React, { useState, useContext } from "react";
+import { StyleSheet, View, TextInput, Text } from "react-native";
 import CommentBarButtons from "./CommentBarButtons";
+import NavContext from "../../../contexts/NavContext";
 
 /*
 To add the comment bar to your components, you need to pass in the callback function
```
Comment (shashankanandkannan) [inline mobile/src/src/components/common/CommentBar/CommentBar.jsx:7]: Maybe briefly mention sendComment here? I mostly added this paragraph to explain which props are callbacks, cause js doesn't have much clarity about data types.

**Comment by shashankanandkannan** [comment]
Looks good!

**Review by shashankanandkannan — APPROVED** [review]

**Review by shashankanandkannan — CHANGES_REQUESTED** [review]
@trentstauff Actually, on second thought, fixing the big comment above the comment bar component is more important than I thought. You should probably either mention that new callback or remove the comment. It's better to not have incomplete comments.

**Review by shashankanandkannan — APPROVED** [review]
👍
